@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Dec 02 21:52:39 +0100 2025
REM SW Build 6140274 on Thu May 22 00:12:29 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim ste_dice_tb_behav -key {Behavioral:sim_dice:Functional:ste_dice_tb} -tclbatch ste_dice_tb.tcl -view D:/2025.1/Projects/Digital circuit design/DCD_Lab3_Dice/Dice/ste_dice_tb_behav.wcfg -log simulate.log"
call xsim  ste_dice_tb_behav -key {Behavioral:sim_dice:Functional:ste_dice_tb} -tclbatch ste_dice_tb.tcl -view D:/2025.1/Projects/Digital circuit design/DCD_Lab3_Dice/Dice/ste_dice_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
